version: "3"

services:
    mock_backend:
        image: stoplight/prism:4
        container_name: recambios_mock
        command: mock --cors -h 0.0.0.0 "/recambios/openapi.yaml"
        ports:
          - "4010:4010"
        volumes:
            - ./openapi:/recambios:ro

    frontend:
        image: swaggerapi/swagger-ui:latest
        container_name: recambios_ui
        ports:
            - "8000:8080"
        environment:
            SWAGGER_JSON: /recambios/openapi.yaml
        volumes:
            - ./openapi:/recambios:ro

    proxy:
        image: caddy:latest
        container_name: recambios_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
        ports:
            - "80:80"
        depends_on:
            - mock_backend